# Generated by Django 5.1.4 on 2025-01-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
