# Generated by Django 5.1.4 on 2025-01-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flashcardset_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='back_side',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='front_side',
            new_name='question',
        ),
    ]
